"""Backdated demo history for the dashboard trend chart (Phase 4 loose end).

**This writes synthetic history. It is modelled data, not observed data.** Present it
that way — the same discipline `docs/PROJECT_PLAN.md` §3 demands for the ROI model and
`RTO_COST_PKR`. Every row it writes is visibly marked (`DEMO`-prefixed tracking numbers,
a reserved `92300900xxxx` phone range) so it can never be mistaken for real traffic and
can be removed again with `--wipe`.

**Why it exists:** `Interaction` and `InterventionOutcome` both take `created_at` from
the Postgres server default, so every row generated by `app.tools.sim` or
`simulate_outcomes` lands on *today*. The 14-day trend chart therefore showed one bar
beside thirteen flat zeros — the weakest thing on the dashboard. Backdating needs
explicit timestamps, which is all this tool really does.

Generation is split in two so the interesting half is testable without a database:
`plan_history()` is pure (seeded RNG in, plain dicts out) and `write_plan()` does
nothing but insert. What the plan aims for:

- **Weekday/weekend shape** — courier volume genuinely dips at the weekend, so the
  chart has texture rather than noise. No artificial growth ramp: a fabricated
  adoption curve would be claiming something the system hasn't earned.
- **A business-hours bias with a real after-hours tail**, so `after_hours_pct` and the
  local-date bucketing in `compute_daily_series` have something honest to report.
- **Coherent chains** — a delay complaint produces an `Intervention`, a failed
  `DeliveryAttempt`, and later an `InterventionOutcome`, so the cases feed, the RTO
  metric, and the trend chart all describe the same events.

**Re-running it is safe, and is the intended habit.** The window ends *yesterday*, so
generated history goes stale at a day per day; left alone for a week, the right third of
the trend chart is empty and reads as though the system stopped working. A plain run
therefore fills only the days that are missing and continues the `DEMO` numbering past
whatever exists — so run it before any demo rather than hoping the last run is still
current.

    python -m app.tools.seed_demo_history                  # fill any missing days (safe to repeat)
    python -m app.tools.seed_demo_history --days 21 --seed 7
    python -m app.tools.seed_demo_history --dry-run        # print the shape, write nothing
    python -m app.tools.seed_demo_history --wipe           # remove everything it wrote
    python -m app.tools.seed_demo_history --wipe && python -m app.tools.seed_demo_history --fresh
"""
import argparse
import random
from datetime import date, datetime, timedelta, timezone
from zoneinfo import ZoneInfo

from app.core import config
from app.core.database import SessionLocal
from app.models.delivery_attempt import DeliveryAttempt
from app.models.interaction import Interaction
from app.models.intervention import Intervention
from app.models.intervention_outcome import InterventionOutcome
from app.models.message import Message

# Reserved markers so demo rows are identifiable and removable. Digits only for the
# phone (it flows through the same validation as a real number); the tracking prefix
# still matches the TRACKING_PATTERN regex in app/graph/nodes.py.
DEMO_PHONE_PREFIX = "92300900"
DEMO_TRACKING_PREFIX = "DEMO"

# Deliberately wider than the dashboard's default 14-day window: history ends
# *yesterday*, so a 14-day generation is already missing its oldest bucket by the time
# you look at it. The slack buys a few days of grace — the actual fix for staleness is
# that a re-run tops up the gap rather than duplicating the window.
DEFAULT_DAYS = 18
DEFAULT_SEED = 42
DEFAULT_MIN_PER_DAY = 6
DEFAULT_MAX_PER_DAY = 16

WEEKEND_VOLUME_FACTOR = 0.55
AFTER_HOURS_SHARE = 0.28
ROMAN_URDU_SHARE = 0.55
INTERVENTION_SUCCESS_RATE = 0.75

# Intent mix, and how likely each is to end up with a human. A delay complaint
# escalates far more often than a status check — a flat rate across intents would
# make the deflection metric meaningless.
INTENT_WEIGHTS = {
    "track_order": 0.46,
    "delay_complaint": 0.30,
    "faq": 0.18,
    "unclear": 0.06,
}
INTENT_ESCALATION_RATE = {
    "track_order": 0.03,
    "delay_complaint": 0.28,
    "faq": 0.05,
    "unclear": 0.22,
}

# Only these produce a corrective intervention — they're the reasons a customer reply
# can actually fix, matching CORRECTIVE_INTENT_TO_ACTION / the notify branch of
# REASON_TO_DECISION.
CORRECTIVE_REASONS = ["customer_unavailable", "incorrect_address", "consignee_requested_reschedule"]

_ENGLISH_PROMPTS = [
    "Where is my parcel?", "Any update on my delivery?", "TRK status please",
    "My order hasn't arrived yet", "When will the rider come?",
]
_ROMAN_URDU_PROMPTS = [
    "Mera parcel kahan hai?", "Abhi tak delivery nahi hui", "Kab tak aayega?",
    "Rider ka koi update?", "Parcel ki location bata dein",
]


def _pick_hour(rng: random.Random, start_hour: int, end_hour: int) -> int:
    """A business-hours-weighted hour of day, with a genuine after-hours tail — that
    tail is the whole point of the after-hours-coverage KPI."""
    if rng.random() < AFTER_HOURS_SHARE:
        after_hours = [h for h in range(24) if not (start_hour <= h < end_hour)]
        return rng.choice(after_hours)
    return rng.randrange(start_hour, end_hour)


def _weighted_choice(rng: random.Random, weights: dict[str, float]) -> str:
    return rng.choices(list(weights), weights=list(weights.values()), k=1)[0]


def plan_history(days: int = DEFAULT_DAYS,
                 seed: int = DEFAULT_SEED,
                 min_per_day: int = DEFAULT_MIN_PER_DAY,
                 max_per_day: int = DEFAULT_MAX_PER_DAY,
                 end_date: date | None = None,
                 tz_name: str | None = None,
                 skip_dates: set[date] | None = None,
                 seq_start: int = 0) -> dict:
    """Build the full set of rows to insert, as plain dicts. Pure: same seed, same
    plan. Timestamps come back tz-aware in the business timezone — `write_plan` stores
    them as-is into `timestamptz` columns, so they bucket into exactly the local day
    they were generated for (see `compute_daily_series._local_date`).

    `skip_dates` and `seq_start` are what make a top-up run safe. Days already holding
    demo rows are left alone rather than doubled, and sequence numbering continues past
    what exists so a second run can't reissue a `DEMO....` tracking number that
    `delivery_attempts` already has under its unique `(tracking_number, attempt_no)`.
    Both are plain arguments so this stays pure and DB-free — `existing_demo_state()`
    is the impure half that supplies them.
    """
    rng = random.Random(seed)
    tz = ZoneInfo(tz_name or config.BUSINESS_HOURS_TIMEZONE)
    start_hour = config.BUSINESS_HOURS_START_HOUR
    end_hour = config.BUSINESS_HOURS_END_HOUR
    skip_dates = skip_dates or set()

    if end_date is None:
        end_date = datetime.now(tz).date()
    # Oldest first, and excluding today: today belongs to the live demo traffic, and
    # overwriting it with synthetic rows would bury the run happening on screen.
    window = [end_date - timedelta(days=offset) for offset in range(days, 0, -1)]
    bucket_dates = [day for day in window if day not in skip_dates]

    interactions: list[dict] = []
    messages: list[dict] = []
    interventions: list[dict] = []
    attempts: list[dict] = []
    outcomes: list[dict] = []
    seq = seq_start

    for day in bucket_dates:
        volume = rng.randint(min_per_day, max_per_day)
        if day.weekday() >= 5:  # Saturday/Sunday
            volume = max(1, round(volume * WEEKEND_VOLUME_FACTOR))

        for _ in range(volume):
            seq += 1
            phone = f"{DEMO_PHONE_PREFIX}{seq % 40:04d}"
            tracking_number = f"{DEMO_TRACKING_PREFIX}{seq:04d}"
            intent = _weighted_choice(rng, INTENT_WEIGHTS)
            escalated = rng.random() < INTENT_ESCALATION_RATE[intent]
            roman_urdu = rng.random() < ROMAN_URDU_SHARE

            at = datetime(
                day.year, day.month, day.day,
                _pick_hour(rng, start_hour, end_hour),
                rng.randrange(60), rng.randrange(60), tzinfo=tz,
            )

            prompt = rng.choice(_ROMAN_URDU_PROMPTS if roman_urdu else _ENGLISH_PROMPTS)
            interactions.append({
                "customer_phone": phone,
                "tracking_number": tracking_number if intent != "faq" else None,
                "intent": intent,
                "decision": "escalate" if escalated else None,
                "resolved_by": "human" if escalated else "bot",
                "escalated": escalated,
                "language": "roman_urdu" if roman_urdu else "english",
                "response_time_ms": rng.randint(700, 3200),
                "created_at": at,
            })
            messages.append({
                "customer_phone": phone, "direction": "in", "body": prompt,
                "tracking_number": tracking_number if intent != "faq" else None,
                "created_at": at,
            })
            messages.append({
                "customer_phone": phone, "direction": "out",
                "body": f"Your parcel {tracking_number} is on its way — thanks for your patience."
                        if intent != "faq" else "Our support hours are 9am to 6pm, seven days a week.",
                "tracking_number": tracking_number if intent != "faq" else None,
                "created_at": at + timedelta(seconds=2),
            })

            # A delay complaint on a customer-fixable reason is what the proactive loop
            # converts: failed attempt -> corrective action -> resolved outcome.
            if intent != "delay_complaint" or escalated:
                continue

            reason = rng.choice(CORRECTIVE_REASONS)
            intervention_id = f"INT-{DEMO_TRACKING_PREFIX}-{seq:04d}"
            action = "update_address" if reason == "incorrect_address" else "reschedule"

            attempts.append({
                "tracking_number": tracking_number, "attempt_no": 1,
                "outcome": "failed", "failure_reason": reason,
                "created_at": at - timedelta(hours=2),
            })
            interventions.append({
                "intervention_id": intervention_id, "tracking_number": tracking_number,
                "action": action,
                "detail": f"Customer reply resolved '{reason}' via {action} (demo history).",
                "created_at": at + timedelta(minutes=3),
            })

            delivered = rng.random() < INTERVENTION_SUCCESS_RATE
            # The redelivery lands a day or two later — that lag is real, and it means
            # the last buckets legitimately have fewer resolved outcomes than
            # interventions, which is what the live data will look like too.
            resolved_at = at + timedelta(days=rng.randint(1, 2), hours=rng.randint(0, 8))
            attempts.append({
                "tracking_number": tracking_number, "attempt_no": 2,
                "outcome": "success" if delivered else "failed",
                "failure_reason": None if delivered else reason,
                "created_at": resolved_at,
            })
            outcomes.append({
                "intervention_id": intervention_id, "tracking_number": tracking_number,
                "outcome": "delivered" if delivered else "still_failed",
                "created_at": resolved_at,
            })

    return {
        "dates": bucket_dates,
        "window": window,
        "skipped": [day for day in window if day in skip_dates],
        "interactions": interactions,
        "messages": messages,
        "interventions": interventions,
        "delivery_attempts": attempts,
        "intervention_outcomes": outcomes,
    }


def existing_demo_state(tz_name: str | None = None) -> tuple[set[date], int]:
    """Which local days already hold demo history, and the highest `DEMO` sequence in
    use. The impure counterpart to `plan_history`'s `skip_dates` / `seq_start`.

    Days are bucketed the same way the trend chart buckets them — local date in the
    business timezone — so "this day is already covered" means the same thing here as
    it does on the chart.
    """
    tz = ZoneInfo(tz_name or config.BUSINESS_HOURS_TIMEZONE)
    db = SessionLocal()
    try:
        rows = (
            db.query(Interaction.created_at, Interaction.tracking_number)
            .filter(Interaction.customer_phone.like(f"{DEMO_PHONE_PREFIX}%"))
            .all()
        )
        # delivery_attempts is the table with the unique (tracking_number, attempt_no)
        # constraint, so it is scanned too rather than inferring the ceiling from
        # interactions alone — an FAQ interaction carries no tracking number, so the
        # highest sequence is not always visible from that side.
        attempt_tracking = [
            row[0] for row in
            db.query(DeliveryAttempt.tracking_number)
            .filter(DeliveryAttempt.tracking_number.like(f"{DEMO_TRACKING_PREFIX}%"))
            .distinct()
            .all()
        ]
    finally:
        db.close()

    def _seq_of(tracking_number: str | None) -> int:
        if not tracking_number or not tracking_number.startswith(DEMO_TRACKING_PREFIX):
            return 0
        suffix = tracking_number[len(DEMO_TRACKING_PREFIX):]
        return int(suffix) if suffix.isdigit() else 0

    days: set[date] = set()
    max_seq = 0
    for created_at, tracking_number in rows:
        at = created_at.replace(tzinfo=timezone.utc) if created_at.tzinfo is None else created_at
        days.add(at.astimezone(tz).date())
        max_seq = max(max_seq, _seq_of(tracking_number))
    for tracking_number in attempt_tracking:
        max_seq = max(max_seq, _seq_of(tracking_number))

    return days, max_seq


def write_plan(plan: dict) -> dict:
    """Insert a plan. `delivery_attempt_id` on an InterventionOutcome is a real FK-ish
    reference, so attempts are flushed first to get their ids before the outcomes that
    point at them."""
    db = SessionLocal()
    try:
        db.add_all(Message(**row) for row in plan["messages"])
        db.add_all(Interaction(**row) for row in plan["interactions"])
        db.add_all(Intervention(**row) for row in plan["interventions"])

        attempts_by_key = {}
        for row in plan["delivery_attempts"]:
            attempt = DeliveryAttempt(**row)
            db.add(attempt)
            attempts_by_key[(row["tracking_number"], row["attempt_no"])] = attempt
        db.flush()  # assigns attempt ids

        for row in plan["intervention_outcomes"]:
            resolving_attempt = attempts_by_key[(row["tracking_number"], 2)]
            db.add(InterventionOutcome(delivery_attempt_id=resolving_attempt.id, **row))

        db.commit()
    finally:
        db.close()

    return {key: len(plan[key]) for key in
            ("messages", "interactions", "interventions", "delivery_attempts", "intervention_outcomes")}


def wipe() -> dict:
    """Remove every row this tool wrote, identified by the reserved demo markers.
    Real traffic is never touched — no real tracking number starts with `DEMO` and no
    real customer sits in the reserved phone range."""
    phone_like = f"{DEMO_PHONE_PREFIX}%"
    tracking_like = f"{DEMO_TRACKING_PREFIX}%"

    db = SessionLocal()
    try:
        deleted = {
            "intervention_outcomes": db.query(InterventionOutcome)
                .filter(InterventionOutcome.tracking_number.like(tracking_like))
                .delete(synchronize_session=False),
            "delivery_attempts": db.query(DeliveryAttempt)
                .filter(DeliveryAttempt.tracking_number.like(tracking_like))
                .delete(synchronize_session=False),
            "interventions": db.query(Intervention)
                .filter(Intervention.tracking_number.like(tracking_like))
                .delete(synchronize_session=False),
            "interactions": db.query(Interaction)
                .filter(Interaction.customer_phone.like(phone_like))
                .delete(synchronize_session=False),
            "messages": db.query(Message)
                .filter(Message.customer_phone.like(phone_like))
                .delete(synchronize_session=False),
        }
        db.commit()
        return deleted
    finally:
        db.close()


def _summarise(plan: dict) -> str:
    by_day = {}
    for interaction in plan["interactions"]:
        key = interaction["created_at"].date()
        by_day[key] = by_day.get(key, 0) + 1
    lines = [f"  {day.isoformat()} ({day.strftime('%a')})  {'#' * by_day.get(day, 0)} {by_day.get(day, 0)}"
             for day in plan["dates"]]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--days", type=int, default=DEFAULT_DAYS,
                        help=f"Days of history to generate, ending yesterday (default {DEFAULT_DAYS})")
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED,
                        help=f"RNG seed — same seed, same data (default {DEFAULT_SEED})")
    parser.add_argument("--min-per-day", type=int, default=DEFAULT_MIN_PER_DAY)
    parser.add_argument("--max-per-day", type=int, default=DEFAULT_MAX_PER_DAY)
    parser.add_argument("--dry-run", action="store_true", help="Print the shape, write nothing")
    parser.add_argument("--fresh", action="store_true",
                        help="Plan the whole window instead of only the missing days. "
                             "Expects an empty slate — pair it with --wipe, or it will "
                             "duplicate days that already exist.")
    parser.add_argument("--wipe", action="store_true",
                        help="Delete previously generated demo history and exit")
    args = parser.parse_args()

    if args.wipe:
        removed = wipe()
        print("Removed demo history: " + ", ".join(f"{v} {k}" for k, v in removed.items()))
        raise SystemExit(0)

    # Top up by default. The window always ends *yesterday*, so history generated once
    # goes stale at a day per day — six days after a run the right third of the chart is
    # empty and reads as though the system stopped working. Re-running used to be unsafe
    # (duplicate days, and a reissued DEMO tracking number violating the unique
    # `(tracking_number, attempt_no)` on delivery_attempts), which is why nobody did.
    # Now it only fills the gap, so it is safe to run before any demo.
    skip_dates, max_seq = ((set(), 0) if args.fresh else existing_demo_state())

    plan = plan_history(days=args.days, seed=args.seed,
                        min_per_day=args.min_per_day, max_per_day=args.max_per_day,
                        skip_dates=skip_dates, seq_start=max_seq)

    if plan["skipped"]:
        print(f"{len(plan['skipped'])} of the last {args.days} days already have demo "
              f"history — leaving them as they are.")

    if not plan["dates"]:
        print("Nothing to fill: the window is already covered.")
        raise SystemExit(0)

    print(f"Planned {len(plan['interactions'])} interactions across "
          f"{len(plan['dates'])} day(s) (seed {args.seed}):")
    print(_summarise(plan))

    if args.dry_run:
        print("\n--dry-run: nothing written.")
        raise SystemExit(0)

    written = write_plan(plan)
    print("\nWrote: " + ", ".join(f"{v} {k}" for k, v in written.items()))
    print("This is MODELLED history, marked with the DEMO prefix — present it as such. "
          "Remove it with --wipe.")
